<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Log\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Models\Pagination\**" />
    <Compile Remove="Pagination\QueryStringParameters\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Models\Pagination\**" />
    <EmbeddedResource Remove="Pagination\QueryStringParameters\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Models\Pagination\**" />
    <Content Remove="Pagination\QueryStringParameters\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Models\Pagination\**" />
    <None Remove="Pagination\QueryStringParameters\**" />
  </ItemGroup>

</Project>
